### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ItssJxstnDe** [kristiyanpts/ox_inventory-bulgar-edition#2]
![image](https://github.com/kristiyanpts/ox_inventory-bulgar-edition/assets/127620206/c570fc4f-0939-4f72-aca7-5af814a6dcba)
Trying to open inventory

**Comment by ItssJxstnDe** [comment]
i replaced ONLY the build from mine to yours

**Comment by d4nizqy** [comment]
pls fix this
